Parameters:
  ProjectName:
    Type: String
    AllowedValues:
      - dummy-cross-ref-project
      - dummy-param-store-project
  S3FirehoseDir:
    Type: String
    Default: dummy_dir
  DatabaseName:
    Type: String
    Default: dummy_database
  TableName:
    Type: String
    Default: dummy

Resources:

  # Glue database
  GlueDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref "AWS::AccountId" # Replacement
      DatabaseInput:
        Name: !Ref "DatabaseName" # Replacement
  # Glue table
  GlueTable:
    Type: "AWS::Glue::Table"
    Properties:
      CatalogId: !Ref "AWS::AccountId"  # Replacement
      DatabaseName: !Ref "GlueDatabase" # Replacement
      TableInput: # Replacement
        Name: !Ref "TableName"
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          EXTERNAL: true
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: name
              Type: string
          Location: !Sub
            - "s3://${S3Bucket}/${S3Dir}"
            - S3Bucket: !Sub "{{resolve:ssm:${ProjectName}-S3FirehoseBucketName}}"
              S3Dir: !Ref "S3FirehoseDir"
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters:
              serialization.format: '1'
          BucketColumns: [ ]
          SortColumns: [ ]
