Parameters:
  ProjectName:
    Type: String
    AllowedValues:
      - dummy-cross-ref-project
      - dummy-param-store-project
  S3FirehoseDir:
    Type: String
    Default: dummy_dir
  DatabaseName:
    Type: String
    Default: dummy_database2
  TableName:
    Type: String
    Default: dummy2

Resources:
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-firehose-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: !Sub "${ProjectName}-firehose-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource: !Sub
                  - "${Arn}/*"
                  - Arn: !ImportValue "S3Arn"
              - Effect: Allow
                Action:
                  - glue:GetTable
                  - glue:GetTableVersion
                  - glue:GetTableVersions
                Resource:
                  - "*"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-firehose-role"
  # Glue database
  GlueDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref "AWS::AccountId" # Replacement
      DatabaseInput:
        Name: !Ref "DatabaseName" # Replacement
  # Glue table
  GlueTable:
    Type: "AWS::Glue::Table"
    Properties:
      CatalogId: !Ref "AWS::AccountId"  # Replacement
      DatabaseName: !Ref "GlueDatabase" # Replacement
      TableInput: # Replacement
        Name: !Ref "TableName"
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          EXTERNAL: true
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
          Location: !Sub
            - "s3://${S3Bucket}/${S3Dir}"
            - S3Bucket: !ImportValue "S3FirehoseBucketName"
              S3Dir: !Ref "S3FirehoseDir"
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters:
              serialization.format: '1'
          BucketColumns: [ ]
          SortColumns: [ ]
  ## ------------- Firehose -------------
  FirehoseMobileAttribution:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyType: AWS_OWNED_CMK
      DeliveryStreamName: !Sub "${ProjectName}-firehose" # Replacement
      DeliveryStreamType: DirectPut                                                          # Replacement
      ExtendedS3DestinationConfiguration:
        RoleARN: !GetAtt "FirehoseRole.Arn"
        BucketARN: !ImportValue "S3Arn"
        Prefix: !Sub "${S3FirehoseDir}/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
        ErrorOutputPrefix: !Sub "${S3FirehoseDir}/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}"
        BufferingHints:
          SizeInMBs: 64
          IntervalInSeconds: 60
        CompressionFormat: UNCOMPRESSED # Record Format変換を使用する場合, 自動的にSnappy圧縮が選択されるため指定しない
        S3BackupMode: Disabled
        DataFormatConversionConfiguration:
          SchemaConfiguration:
            CatalogId: !Ref "AWS::AccountId"
            RoleARN: !GetAtt "FirehoseRole.Arn"
            DatabaseName: !Ref "GlueDatabase"
            TableName: !Ref "GlueTable"
            Region: !Ref "AWS::Region"
            VersionId: LATEST
          InputFormatConfiguration:
            Deserializer:
              OpenXJsonSerDe: { }
          OutputFormatConfiguration:
            Serializer:
              ParquetSerDe: { }
          Enabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}"
