Parameters:
  ProjectName:
    Type: String
    AllowedValues:
      - dummy-cross-reference-paramter-project
      - dummy-paramter-store-project

Resources:
  ComputeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-instance-role
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  ComputeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ProjectName}-instance-profile
      Roles:
        - !Ref "ComputeInstanceRole"
  ## ------------- Outputs -------------
Outputs:
  ComputeInstanceProfileArn:
    Value: !Sub "${ComputeInstanceProfile.Arn}"
    Export:
      Name: ComputeInstanceProfileArn
